name:                haskell-http
version:             0.1.0.0
github:              "dabliuw22/haskell-http"
license:             BSD3
author:              "Will Leyton"
maintainer:          "wleylop22@gmail.com"
copyright:           "2020 Will Leyton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dabliuw22/haskell-http#readme>

dependencies:
- base
- hspec
- mtl
- async
- time
- text
- uuid
- bytestring
- bytestring-conversion
- exceptions
- postgresql-simple
- postgresql-simple-migration
- resource-pool
- aeson
- servant
- servant-server
- katip
- wai
- wai-cors
- warp
- directory
- time

default-extensions:
- TemplateHaskell

library:
  source-dirs: src

executables:
  haskell-http-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-http
    - text

tests:
  haskell-http-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-http
    - hspec
    - text
