name: haskell-http
version: 0.1.0.0
github: "dabliuw22/haskell-http"
license: BSD3
author: "Will Leyton"
maintainer: "wleylop22@gmail.com"
copyright: "2020 Will Leyton"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dabliuw22/haskell-http#readme>

dependencies:
  - base >= 4.5 && < 5
  - hspec
  - mtl >= 2.0.1 && < 2.3
  - async
  - time >= 1.9.3 && < 1.10
  - text >= 1.2.2.1 && < 1.3
  - transformers
  - uuid >= 1.3.13 && < 1.4
  - bytestring >= 0.10.10 && < 0.11
  - bytestring-conversion >= 0.1 && < 0.3.2
  - exceptions
  - free
  - postgresql-simple
  - resource-pool
  - aeson
  - servant
  - servant-server
  - servant-auth-server
  - jose
  - katip >= 0.1.0.0 && < 0.8.6.0
  - wai
  - wai-cors
  - warp
  - http-types
  - directory
  - lens >= 4.0 && < 4.20
  - QuickCheck
  - envs
  - postgres
  - logger
  - products-domain
  - products-application
  - products-adapter

library:
  source-dirs: src

executables:
  haskell-http-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - haskell-http

tests:
  haskell-http-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-http
      - hspec
      - text
