name: Haskell CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: 🧰 Setup Stack
      uses: actions/setup-haskell@v1.1.4
      with:
        ghc-version: '8.8.3'
        enable-stack: true
        stack-version: 'latest'
    - name: 💽 Install libpq
      run: sudo apt-get install libpq-dev
    - name: 🔑 Cache Key
      id: cache_key
      run: echo "::set-output name=key::$(md5sum stack.yaml | awk '{print $1}')"
    - name: 💾 Cache Dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}
    - name: 💽 Install Ormolu
      run: stack install ormolu --resolver=lts-16.3
    - name: 📃 Check Formatter
      run: ormolu --mode check $(find . -name '*.hs')
    - name: 🔨 Stack Install
      run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
    - name: 🛠 Stack Build
      run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    - name: ✅ Stack Test
      run: stack test --system-ghc
