name: Haskell CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Stack
      uses: actions/setup-haskell@v1.1.4
      with:
        ghc-version: '8.8.3'
        enable-stack: true
        stack-version: 'latest'
    - name: Install libpq
      run: sudo apt-get install libpq-dev
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: |
          ~/.stack
          .stack-work/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Run test
      run: stack test
